/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import o.lnt.domain.Indexes;
import o.lnt.domain.Keys;
import o.lnt.domain.LntoUsermgmt;
import o.lnt.domain.tables.records.AddressRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address extends TableImpl<AddressRecord> {

    private static final long serialVersionUID = 352338948;

    /**
     * The reference instance of <code>lnto_usermgmt.address</code>
     */
    public static final Address ADDRESS = new Address();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressRecord> getRecordType() {
        return AddressRecord.class;
    }

    /**
     * The column <code>lnto_usermgmt.address.AddressID</code>.
     */
    public final TableField<AddressRecord, Integer> ADDRESSID = createField("AddressID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lnto_usermgmt.address.AddressType</code>.
     */
    public final TableField<AddressRecord, String> ADDRESSTYPE = createField("AddressType", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.PersonID</code>.
     */
    public final TableField<AddressRecord, Integer> PERSONID = createField("PersonID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.IsDefault</code>.
     */
    public final TableField<AddressRecord, Byte> ISDEFAULT = createField("IsDefault", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.Country</code>.
     */
    public final TableField<AddressRecord, String> COUNTRY = createField("Country", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.ZipPostCode</code>.
     */
    public final TableField<AddressRecord, String> ZIPPOSTCODE = createField("ZipPostCode", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>lnto_usermgmt.address.ProvinceStateCounty</code>.
     */
    public final TableField<AddressRecord, String> PROVINCESTATECOUNTY = createField("ProvinceStateCounty", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>lnto_usermgmt.address.CityTownVillage</code>.
     */
    public final TableField<AddressRecord, String> CITYTOWNVILLAGE = createField("CityTownVillage", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.StreetRoadBlock</code>.
     */
    public final TableField<AddressRecord, String> STREETROADBLOCK = createField("StreetRoadBlock", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.HouseBuilding</code>.
     */
    public final TableField<AddressRecord, String> HOUSEBUILDING = createField("HouseBuilding", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.address.Other</code>.
     */
    public final TableField<AddressRecord, String> OTHER = createField("Other", org.jooq.impl.SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>lnto_usermgmt.address.Longitude</code>.
     */
    public final TableField<AddressRecord, BigDecimal> LONGITUDE = createField("Longitude", org.jooq.impl.SQLDataType.DECIMAL(11, 8), this, "");

    /**
     * The column <code>lnto_usermgmt.address.Latitude</code>.
     */
    public final TableField<AddressRecord, BigDecimal> LATITUDE = createField("Latitude", org.jooq.impl.SQLDataType.DECIMAL(11, 8), this, "");

    /**
     * Create a <code>lnto_usermgmt.address</code> table reference
     */
    public Address() {
        this(DSL.name("address"), null);
    }

    /**
     * Create an aliased <code>lnto_usermgmt.address</code> table reference
     */
    public Address(String alias) {
        this(DSL.name(alias), ADDRESS);
    }

    /**
     * Create an aliased <code>lnto_usermgmt.address</code> table reference
     */
    public Address(Name alias) {
        this(alias, ADDRESS);
    }

    private Address(Name alias, Table<AddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private Address(Name alias, Table<AddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Address(Table<O> child, ForeignKey<O, AddressRecord> key) {
        super(child, key, ADDRESS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return LntoUsermgmt.LNTO_USERMGMT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ADDRESS_FK_PHONE_PERSON00, Indexes.ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AddressRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AddressRecord> getPrimaryKey() {
        return Keys.KEY_ADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AddressRecord>> getKeys() {
        return Arrays.<UniqueKey<AddressRecord>>asList(Keys.KEY_ADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AddressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AddressRecord, ?>>asList(Keys.FK_PHONE_PERSON00);
    }

    public Person person() {
        return new Person(this, Keys.FK_PHONE_PERSON00);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address as(String alias) {
        return new Address(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address as(Name alias) {
        return new Address(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Address rename(String name) {
        return new Address(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Address rename(Name name) {
        return new Address(name, null);
    }
}
