/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import o.lnt.domain.DefaultSchema;
import o.lnt.domain.Indexes;
import o.lnt.domain.tables.records.PersonRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person extends TableImpl<PersonRecord> {

    private static final long serialVersionUID = 1920992956;

    /**
     * The reference instance of <code>person</code>
     */
    public static final Person PERSON = new Person();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersonRecord> getRecordType() {
        return PersonRecord.class;
    }

    /**
     * The column <code>person.PersonID</code>.
     */
    public final TableField<PersonRecord, Integer> PERSONID = createField("PersonID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>person.FirstName</code>.
     */
    public final TableField<PersonRecord, String> FIRSTNAME = createField("FirstName", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>person.LastName</code>.
     */
    public final TableField<PersonRecord, String> LASTNAME = createField("LastName", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>person.MiddleName</code>.
     */
    public final TableField<PersonRecord, String> MIDDLENAME = createField("MiddleName", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>person.Gender</code>.
     */
    public final TableField<PersonRecord, String> GENDER = createField("Gender", org.jooq.impl.SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>person.Birthday</code>.
     */
    public final TableField<PersonRecord, LocalDateTime> BIRTHDAY = createField("Birthday", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>person.Title</code>.
     */
    public final TableField<PersonRecord, String> TITLE = createField("Title", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>person.Suffix</code>.
     */
    public final TableField<PersonRecord, String> SUFFIX = createField("Suffix", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>person.Active</code>.
     */
    public final TableField<PersonRecord, Byte> ACTIVE = createField("Active", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>person.Uuid</code>.
     */
    public final TableField<PersonRecord, String> UUID = createField("Uuid", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * Create a <code>person</code> table reference
     */
    public Person() {
        this(DSL.name("person"), null);
    }

    /**
     * Create an aliased <code>person</code> table reference
     */
    public Person(String alias) {
        this(DSL.name(alias), PERSON);
    }

    /**
     * Create an aliased <code>person</code> table reference
     */
    public Person(Name alias) {
        this(alias, PERSON);
    }

    private Person(Name alias, Table<PersonRecord> aliased) {
        this(alias, aliased, null);
    }

    private Person(Name alias, Table<PersonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PERSON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PersonRecord, Integer> getIdentity() {
        return Internal.createIdentity(o.lnt.domain.tables.Person.PERSON, o.lnt.domain.tables.Person.PERSON.PERSONID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersonRecord> getPrimaryKey() {
        return Internal.createUniqueKey(o.lnt.domain.tables.Person.PERSON, "KEY_person_PRIMARY", o.lnt.domain.tables.Person.PERSON.PERSONID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersonRecord>> getKeys() {
        return Arrays.<UniqueKey<PersonRecord>>asList(
              Internal.createUniqueKey(o.lnt.domain.tables.Person.PERSON, "KEY_person_PRIMARY", o.lnt.domain.tables.Person.PERSON.PERSONID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person as(String alias) {
        return new Person(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person as(Name alias) {
        return new Person(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Person rename(String name) {
        return new Person(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Person rename(Name name) {
        return new Person(name, null);
    }
}
