/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import o.lnt.domain.Indexes;
import o.lnt.domain.Keys;
import o.lnt.domain.LntoUsermgmt;
import o.lnt.domain.tables.records.PhoneRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Phone extends TableImpl<PhoneRecord> {

    private static final long serialVersionUID = -1285760933;

    /**
     * The reference instance of <code>lnto_usermgmt.phone</code>
     */
    public static final Phone PHONE = new Phone();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhoneRecord> getRecordType() {
        return PhoneRecord.class;
    }

    /**
     * The column <code>lnto_usermgmt.phone.PhoneID</code>.
     */
    public final TableField<PhoneRecord, Integer> PHONEID = createField("PhoneID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lnto_usermgmt.phone.AddressType</code>.
     */
    public final TableField<PhoneRecord, String> ADDRESSTYPE = createField("AddressType", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.phone.PhoneNumber</code>.
     */
    public final TableField<PhoneRecord, String> PHONENUMBER = createField("PhoneNumber", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>lnto_usermgmt.phone.PersonID</code>.
     */
    public final TableField<PhoneRecord, Integer> PERSONID = createField("PersonID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lnto_usermgmt.phone.IsDefault</code>.
     */
    public final TableField<PhoneRecord, Byte> ISDEFAULT = createField("IsDefault", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>lnto_usermgmt.phone</code> table reference
     */
    public Phone() {
        this(DSL.name("phone"), null);
    }

    /**
     * Create an aliased <code>lnto_usermgmt.phone</code> table reference
     */
    public Phone(String alias) {
        this(DSL.name(alias), PHONE);
    }

    /**
     * Create an aliased <code>lnto_usermgmt.phone</code> table reference
     */
    public Phone(Name alias) {
        this(alias, PHONE);
    }

    private Phone(Name alias, Table<PhoneRecord> aliased) {
        this(alias, aliased, null);
    }

    private Phone(Name alias, Table<PhoneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Phone(Table<O> child, ForeignKey<O, PhoneRecord> key) {
        super(child, key, PHONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return LntoUsermgmt.LNTO_USERMGMT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PHONE_FK_PHONE_PERSON, Indexes.PHONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PhoneRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PhoneRecord> getPrimaryKey() {
        return Keys.KEY_PHONE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PhoneRecord>> getKeys() {
        return Arrays.<UniqueKey<PhoneRecord>>asList(Keys.KEY_PHONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PhoneRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PhoneRecord, ?>>asList(Keys.FK_PHONE_PERSON);
    }

    public Person person() {
        return new Person(this, Keys.FK_PHONE_PERSON);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Phone as(String alias) {
        return new Phone(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Phone as(Name alias) {
        return new Phone(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Phone rename(String name) {
        return new Phone(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Phone rename(Name name) {
        return new Phone(name, null);
    }
}
