/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain.tables.records;


import javax.annotation.Generated;

import o.lnt.domain.tables.Email;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecord extends UpdatableRecordImpl<EmailRecord> implements Record5<Integer, String, String, Integer, Byte> {

    private static final long serialVersionUID = 893993881;

    /**
     * Setter for <code>lnto_usermgmt.email.EmailID</code>.
     */
    public void setEmailid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lnto_usermgmt.email.EmailID</code>.
     */
    public Integer getEmailid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lnto_usermgmt.email.AddressType</code>.
     */
    public void setAddresstype(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lnto_usermgmt.email.AddressType</code>.
     */
    public String getAddresstype() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lnto_usermgmt.email.EmailAddress</code>.
     */
    public void setEmailaddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lnto_usermgmt.email.EmailAddress</code>.
     */
    public String getEmailaddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lnto_usermgmt.email.PersonID</code>.
     */
    public void setPersonid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lnto_usermgmt.email.PersonID</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>lnto_usermgmt.email.IsDefault</code>.
     */
    public void setIsdefault(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>lnto_usermgmt.email.IsDefault</code>.
     */
    public Byte getIsdefault() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Email.EMAIL.EMAILID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Email.EMAIL.ADDRESSTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Email.EMAIL.EMAILADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Email.EMAIL.PERSONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Email.EMAIL.ISDEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEmailid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddresstype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmailaddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsdefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmailid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddresstype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmailaddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPersonid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsdefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value1(Integer value) {
        setEmailid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value2(String value) {
        setAddresstype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value3(String value) {
        setEmailaddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value4(Integer value) {
        setPersonid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord value5(Byte value) {
        setIsdefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailRecord values(Integer value1, String value2, String value3, Integer value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailRecord
     */
    public EmailRecord() {
        super(Email.EMAIL);
    }

    /**
     * Create a detached, initialised EmailRecord
     */
    public EmailRecord(Integer emailid, String addresstype, String emailaddress, Integer personid, Byte isdefault) {
        super(Email.EMAIL);

        set(0, emailid);
        set(1, addresstype);
        set(2, emailaddress);
        set(3, personid);
        set(4, isdefault);
    }
}
