/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain;


import javax.annotation.Generated;

import o.lnt.domain.tables.Address;
import o.lnt.domain.tables.Email;
import o.lnt.domain.tables.Person;
import o.lnt.domain.tables.Phone;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>lnto_usermgmt</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_FK_PHONE_PERSON00 = Indexes0.ADDRESS_FK_PHONE_PERSON00;
    public static final Index ADDRESS_PRIMARY = Indexes0.ADDRESS_PRIMARY;
    public static final Index EMAIL_FK_PHONE_PERSON0 = Indexes0.EMAIL_FK_PHONE_PERSON0;
    public static final Index EMAIL_PRIMARY = Indexes0.EMAIL_PRIMARY;
    public static final Index PERSON_PRIMARY = Indexes0.PERSON_PRIMARY;
    public static final Index PHONE_FK_PHONE_PERSON = Indexes0.PHONE_FK_PHONE_PERSON;
    public static final Index PHONE_PRIMARY = Indexes0.PHONE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADDRESS_FK_PHONE_PERSON00 = Internal.createIndex("fk_Phone_Person00", Address.ADDRESS, new OrderField[] { Address.ADDRESS.PERSONID }, false);
        public static Index ADDRESS_PRIMARY = Internal.createIndex("PRIMARY", Address.ADDRESS, new OrderField[] { Address.ADDRESS.ADDRESSID, Address.ADDRESS.PERSONID }, true);
        public static Index EMAIL_FK_PHONE_PERSON0 = Internal.createIndex("fk_Phone_Person0", Email.EMAIL, new OrderField[] { Email.EMAIL.PERSONID }, false);
        public static Index EMAIL_PRIMARY = Internal.createIndex("PRIMARY", Email.EMAIL, new OrderField[] { Email.EMAIL.EMAILID, Email.EMAIL.PERSONID }, true);
        public static Index PERSON_PRIMARY = Internal.createIndex("PRIMARY", Person.PERSON, new OrderField[] { Person.PERSON.PERSONID }, true);
        public static Index PHONE_FK_PHONE_PERSON = Internal.createIndex("fk_Phone_Person", Phone.PHONE, new OrderField[] { Phone.PHONE.PERSONID }, false);
        public static Index PHONE_PRIMARY = Internal.createIndex("PRIMARY", Phone.PHONE, new OrderField[] { Phone.PHONE.PHONEID, Phone.PHONE.PERSONID }, true);
    }
}
