/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import o.lnt.domain.tables.Address;
import o.lnt.domain.tables.Email;
import o.lnt.domain.tables.Person;
import o.lnt.domain.tables.Phone;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LntoUsermgmt extends SchemaImpl {

    private static final long serialVersionUID = 73106436;

    /**
     * The reference instance of <code>lnto_usermgmt</code>
     */
    public static final LntoUsermgmt LNTO_USERMGMT = new LntoUsermgmt();

    /**
     * The table <code>lnto_usermgmt.address</code>.
     */
    public final Address ADDRESS = o.lnt.domain.tables.Address.ADDRESS;

    /**
     * The table <code>lnto_usermgmt.email</code>.
     */
    public final Email EMAIL = o.lnt.domain.tables.Email.EMAIL;

    /**
     * The table <code>lnto_usermgmt.person</code>.
     */
    public final Person PERSON = o.lnt.domain.tables.Person.PERSON;

    /**
     * The table <code>lnto_usermgmt.phone</code>.
     */
    public final Phone PHONE = o.lnt.domain.tables.Phone.PHONE;

    /**
     * No further instances allowed
     */
    private LntoUsermgmt() {
        super("lnto_usermgmt", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Email.EMAIL,
            Person.PERSON,
            Phone.PHONE);
    }
}
