/*
 * This file is generated by jOOQ.
 */
package o.lnt.domain;


import javax.annotation.Generated;

import o.lnt.domain.tables.Address;
import o.lnt.domain.tables.Email;
import o.lnt.domain.tables.Person;
import o.lnt.domain.tables.Phone;


/**
 * Convenience access to all tables in lnto_usermgmt
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>lnto_usermgmt.address</code>.
     */
    public static final Address ADDRESS = o.lnt.domain.tables.Address.ADDRESS;

    /**
     * The table <code>lnto_usermgmt.email</code>.
     */
    public static final Email EMAIL = o.lnt.domain.tables.Email.EMAIL;

    /**
     * The table <code>lnto_usermgmt.person</code>.
     */
    public static final Person PERSON = o.lnt.domain.tables.Person.PERSON;

    /**
     * The table <code>lnto_usermgmt.phone</code>.
     */
    public static final Phone PHONE = o.lnt.domain.tables.Phone.PHONE;
}
